# Generated by Django 4.2.6 on 2023-12-01 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupdata',
            name='temp',
        ),
    ]
